version: "3"

services:

  social:
    image: teknologist/ubuntu-jdk7-exo-mysql
    depends_on:
      - mysql
    expose:
      - "8080"
    environment:
      - MYSQL_DATABASE=${SOCIAL_DB_NAME:-exo}
      - MYSQL_USER=${SOCIAL_DB_USER:-exo}
      - MYSQL_PASSWORD=${SOCIAL_DB_PASS:-changeme}

      - VIRTUAL_HOST=${SOCIAL_HOST:-social.example.com}
      - VIRTUAL_NETWORK=back-tier
      - VIRTUAL_PORT=8080

      - LETSENCRYPT_HOST=${SOCIAL_HOST:-social.example.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-first.last@example.com}
    volumes:
      - exodata:/srv/exo
    networks:
      - back-tier
    restart: on-failure:5

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-changeme}

      - MYSQL_DATABASE=${SOCIAL_DB_NAME:-exo}
      - MYSQL_USER=${SOCIAL_DB_USER:-exo}
      - MYSQL_PASSWORD=${SOCIAL_DB_PASS:-changeme}
    volumes:
      - social_db:/var/lib/mysql
    networks:
      - back-tier
    restart: on-failure:5

networks:
  back-tier:
    external: true

volumes:
  social_db:
    driver: local
  exodata:
    driver: local
