version: "3"

services:

  social:
    image: exoplatform/exo-community:4.2
    depends_on:
      - mysql
    environment:
      - EXO_PROXY_VHOST=${SOCIAL_HOST:-social.example.com}
      - EXO_PROXY_PORT=80
      - EXO_PROXY_SSL="false"
      - EXO_DB_TYPE=mysql
      - EXO_DB_HOST=mysql
      - EXO_DB_NAME=${SOCIAL_DB_NAME:-exo}
      - EXO_DB_USER=${SOCIAL_DB_USER:-exo}
      - EXO_DB_PASSWORD=${SOCIAL_DB_PASS:-changeme}
      #- EXO_ADDONS_LIST=""

      - VIRTUAL_HOST=${SOCIAL_HOST:-social.example.com}
      - VIRTUAL_NETWORK=back-tier
      - VIRTUAL_PORT=8080

      - LETSENCRYPT_HOST=${SOCIAL_HOST:-social.example.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-first.last@example.com}
    volumes:
      - exodata:/srv/exo
      - exologs:/var/log/exo
    networks:
      - back-tier
    restart: on-failure:5

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-changeme}

      - MYSQL_DATABASE=${SOCIAL_DB_NAME:-exo}
      - MYSQL_USER=${SOCIAL_DB_USER:-exo}
      - MYSQL_PASSWORD=${SOCIAL_DB_PASS:-changeme}
    volumes:
      - social_db:/var/lib/mysql
    networks:
      - back-tier
    restart: on-failure:5

networks:
  back-tier:
    external: true

volumes:
  social_db:
    driver: local
  exodata:
    driver: local
  exologs:
    driver: local
