version: "3"

services:

  activiti:
    image: exolyte/activiti
    container_name: activiti
    expose:
      - "8080"
    volumes:
      - /usr/bin/docker:/bin/docker
      - /var/run/docker.sock:/run/docker.sock
    environment:
      - TOMCAT_ADMIN_USER=admin
      - TOMCAT_ADMIN_PASSWORD=${TOMCAT_ADMIN_PASSWORD:-admin}
      - DB_TYPE=${BPM_DB_TYPE:-mysql}
      - DB_HOST=${BPM_DB_HOST:-mysql-activiti}
      - DB_PORT=${BPM_DB_PORT:-3306}
      - DB_NAME=${BPM_DB_NAME:-activiti}
      - DB_USER=${BPM_DB_USER:-bpm}
      - DB_PASS=${BPM_DB_PASS:-changeme}

      - VIRTUAL_HOST=${BPM_HOST:-bpm.example.com}
      - VIRTUAL_NETWORK=back-tier
      - VIRTUAL_PORT=8080

      - LETSENCRYPT_HOST=${BPM_HOST:-bpm.example.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-first.last@example.com}
    networks:
      - back-tier
    depends_on:
      - mysql-activiti
    # if running on a local vm
    #ports:
    #  - 8080:8080

  mysql-activiti:
    image: mysql:5.7
    volumes:
      - bpm_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-changeme}
      - MYSQL_DATABASE=${BPM_DB_NAME:-activiti}
      - MYSQL_USER=${BPM_DB_USER:-bpm}
      - MYSQL_PASSWORD=${BPM_DB_PASS:-changeme}
    networks:
      - back-tier
    restart: on-failure:5

networks:
  back-tier:
    external: true

volumes:
  bpm_db:
    driver: local
