version: "2"

services:

  jenkinsmaster:
    image: jenkins:alpine
    expose:
      - 8080
      - 50000
    volumes:
      - jenkins:/var/jenkins_home:rw
    environment:
      JAVA_OPTS: "-Xmx8192m"

      VIRTUAL_HOST: jenkins.example.com
      VIRTUAL_PORT: 8080
      VIRTUAL_NETWORK: back-tier

      LETSENCRYPT_HOST: jenkins.example.com
      LETSENCRYPT_EMAIL: first.last@example.com
    networks:
      - back-tier
    #restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'git.example.com'
    ## Embedded nginx config is located at /var/opt/gitlab/nginx/conf
    ##   Use docker cp container_name:/var/opt/gitlab/nginx/conf/gitlab-http.conf localdir
    ##   Use docker cp container_name:/var/opt/gitlab/nginx/conf/nginx.conf localdir
    ## Gitlab config is in etc/gitlab
    ##   Use docker cp container_name:/etc/gitlab/gitlab.rb localdir
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.example.com'
        gitlab_rails['gravatar_enabled'] = false
        nginx['redirect_http_to_https'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {"X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        nginx['real_ip_trusted_addresses'] = [ '192.168.1.0/24', '192.168.2.1', '2001:0db8::/32' ]
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'
        ## SMTP config
        gitlab_rails['smtp_enable'] = false
        gitlab_rails['smtp_address'] = "smtp-mail.example.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "username@example.com"
        gitlab_rails['smtp_password'] = "password"
        gitlab_rails['smtp_domain'] = "smtp-mail.example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        ## Rails Time Zone config
        # gitlab_rails['time_zone'] = 'UTC'
        # gitlab_rails['gitlab_email_enabled'] = true
        # gitlab_rails['gitlab_email_from'] = 'notifications@example.com'
        # gitlab_rails['gitlab_email_display_name'] = 'Example'
        # gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
        ## Reply by email config
        # Allow users to comment on issues and merge requests by replying to notification emails.
        # For documentation on how to set this up, see http://doc.gitlab.com/ce/incoming_email/README.html
        # gitlab_rails['incoming_email_enabled'] = true
        #
        ## The email address including the `%{key}` placeholder that will be replaced to reference the item being replied to.
        ## The placeholder can be omitted but if present, it must appear in the "user" part of the address (before the `@`).
        # gitlab_rails['incoming_email_address'] = "gitlab-incoming+%{key}@example.com"
        #
        ## Email account username and password config
        ## With third party providers, this is usually the full email address.
        ## With self-hosted email servers, this is usually the user part of the email address.
        # gitlab_rails['incoming_email_email'] = "gitlab-incoming@example.com"
        # gitlab_rails['incoming_email_password'] = "[REDACTED]"
        #
        ## IMAP server host, port, SSL, and StartTLS config
        # gitlab_rails['incoming_email_host'] = "imap.example.com"
        # gitlab_rails['incoming_email_port'] = 993
        # gitlab_rails['incoming_email_ssl'] = true
        # gitlab_rails['incoming_email_start_tls'] = false

      VIRTUAL_HOST: git.example.com
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: back-tier

      LETSENCRYPT_HOST: git.example.com
      LETSENCRYPT_EMAIL: first.last@example.com
    volumes:
      #- '/srv/gitlab/config:/etc/gitlab'
      #- '/srv/gitlab/logs:/var/log/gitlab'
      #- '/srv/gitlab/data:/var/opt/gitlab'
      - gitlab_config:/etc/gitlab:rw
      - gitlab:/var/opt/gitlab:rw
    networks:
      - back-tier
    #restart: always

volumes:
  gitlab:
    driver: local
  gitlab_config:
    driver: local
  jenkins:
    driver: local

networks:
  back-tier:
    external: true
