version: "3"

services:

  ghost:
    image: ptimof/ghost
    container_name: ghost
    volumes:
      - webcontent:/var/lib/ghost
    environment:
      - VIRTUAL_HOST=${BLOG_HOST:-blog.example.com}
      - VIRTUAL_NETWORK=back-tier
      - VIRTUAL_PORT=2368

      - LETSENCRYPT_HOST=${BLOG_HOST:-blog.example.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-first.last@example.com}

      - GHOST_URL=http://${BLOG_HOST:-blog.example.com}
    command: npm start --production
    networks:
      - back-tier
    # if testing in a local vm
    #ports:
    #  - 2368:2368

networks:
  back-tier:
    external: true

# External volumes
volumes:
  webcontent:
    external:
      name: docroot
