---
# Debian Vars

admin_user: dev

docker_required_packages:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg-agent"
  - "software-properties-common"
  - "python3-pip"
  - "virtualenv"
  - "python3-setuptools"

docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"

docker_repo: "https://download.docker.com/linux/ubuntu"

docker_packages:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
