---
machines:
  vb:
    count: 1
    user: "vagrant"
    cpus: 2
    memory: 8192
    disk: 120
  aws:
    count: 1
    region: "us-east-1"
    #--------------------------------------------------------------
    # Ubuntu AMIs -- https://cloud-images.ubuntu.com/locator/ec2/
    #--------------------------------------------------------------
    # us-east-1, bionic, 18.04 LTS, amd64, hvm:ebs-ssd, 20221201, ami-061dbd1209944525c, hvm, ENA
    # us-east-1, xenial, 16.04 LTS, amd64, hvm:ebs-ssd, 20210928, ami-0b0ea68c435eb488d, hvm, ENA
    # us-east-1, trusty, 14.04 LTS, amd64, hvm:ebs-ssd, 20191107, ami-000b3a073fc20e415, hvm, ENA
    # us-east-1, trusty, 14.04 LTS, amd64, hvm:ebs-io1, 20191107, ami-06b9259c69d8ed7f3, hvm, ENA
    # us-east-1, trusty, 14.04 LTS, amd64, hvm:ebs,     20191107, ami-07957d39ebba800d5, hvm, ENA

    # following ami not supported for r4.large, m5.large, r4.xlarge
    # us-east-1 xenial  16.04 LTS amd64 hvm:instance-store  20210928  ami-0059b7cd9f67d8050  hvm ENA
    # us-east-1 trusty  14.04 LTS amd64 hvm:instance-store  20191107  ami-0d65710e46db3c637  hvm ENA

    # The following AMI cannot be used on r5.large since r5.large requires an ENA (Elastic Network Adapter)
    ami: "ami-f4cc1de2"
    user: "ubuntu"
    security_groups: "sg-xxxyyyzz"
    keypair_name: "my_key_pair"
    volume_size: 30
    instance_type: r4.large
    spot_price: "0.10"
    subnet_id: "subnet-xxxyyyzz"
    eip: "10.0.0.0"
    eip_allocation_id: "eipalloc-xxxyyyzz"
  azure:
    count: 1
    user: "vagrant"
    vmtype: D2_v2
