---
machines:
  vb:
    count: 1
    user: "vagrant"
    cpus: 2
    memory: 8192
    disk: 120
  aws:
    count: 1
    region: "us-east-1"
    ami: "ami-f4cc1de2"
    user: "ubuntu"
    security_groups: "sg-xxxyyyzz"
    keypair_name: "my_key_pair"
    volume_size: 30
    instance_type: r4.large
    spot_price: "0.15"
    subnet_id: "subnet-xxxyyyzz"
    eip: "10.0.0.0"
    eip_allocation_id: "eipalloc-xxxyyyzz"
  azure:
    count: 1
    user: "vagrant"
    vmtype: D2_v2
