version: "3"

services:

  nginx:
    image: exolyte/nginx-ldap
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "LDAP_SERVER=${LDAP_SERVER:-idp:10389}"
      - "LDAP_SEARCH_BASE_DN=${LDAP_SEARCH_BASE_DN:-ou=Users,dc=wso2,dc=org}"
      - "LDAP_USER_ATTRIBUTE_LIST=${LDAP_USER_ATTRIBUTE_LIST:-uid,userPassword,givenName,sn,mail,mobile,telephoneNumber}"
      - "LDAP_USER_SEARCHFILTER=${LDAP_USER_SEARCHFILTER:-objectclass=inetOrgPerson}"
      - "LDAP_GROUP_ATTRIBUTE_DN=${LDAP_GROUP_ATTRIBUTE_DN:-member}"
      - "LDAP_BIND_DN=${LDAP_BIND_DN:-uid=admin,ou=system}"
      - "LDAP_BIND_DN_PASSWORD=${LDAP_BIND_DN_PASSWORD:-admin}"
    volumes:
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d:ro
      - content:/usr/share/nginx/html:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - vhostd:/etc/nginx/vhost.d:ro
    networks:
      - proxy-tier
      - back-tier
    logging:
      options:
        max-size: ${NGINX_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_LOG_MAX_FILE:-10}
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "../../../config/dockergen/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      # needed volumes fron nginx container
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d:rw
      - htpasswd:/etc/nginx/htpasswd:ro
      - vhostd:/etc/nginx/vhost.d:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # needed volumes fron nginx container
      - certs:/etc/nginx/certs:rw
      - content:/usr/share/nginx/html:rw
      - vhostd:/etc/nginx/vhost.d:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - NGINX_PROXY_CONTAINER=nginx
    restart: always

  idp:
    image: exolyte/wso2is
    container_name: idp
    environment:
      - VIRTUAL_HOST=${IAM_HOST:-idp.example.com}
      - VIRTUAL_NETWORK=back-tier
      - VIRTUAL_PORT=9443
      - VIRTUAL_PROTO=https

      - LETSENCRYPT_HOST=${IAM_HOST:-idp.example.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-first.last@example.com}
    networks:
      - back-tier
    restart: always

networks:
  proxy-tier:
    external: true
  back-tier:
    external: true

# Visit https://docs.docker.com/engine/reference/commandline/volume_create/
volumes:
  certs:
  confd:
  content:
  htpasswd:
  vhostd:
    driver: local
    driver_opts:
      type: none
      device: ../../../config/nginx/vhost.d
      o: bind
  