---
- include_vars: "{{ ansible_os_family }}Vars.yml"

# docker-compose installation tasks
- include: "{{ ansible_os_family }}Tasks.yml"

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Determine docker-compose version
  shell: docker-compose version --short
  register: compose_version

- name: "Install bash completion for docker-compose version: {{compose_version.stdout}}"
  get_url: 
    url=https://raw.githubusercontent.com/docker/compose/{{compose_version.stdout}}/contrib/completion/bash/docker-compose
    dest=/etc/bash_completion.d/docker-compose
    mode=0644
  ignore_errors: true
