---
- name: Setup Docker Host
  hosts: virtualbox:aws
  become: true
  roles:
    - ansible-docker
    - ansible-python-pip
    - ansible-awscli
    - ansible-docker-compose
    - ansible-oracle-java8
    - ansible-confluent-oss