---
- name: Import Docker GPG key
  apt_key: id={{docker_repo_key}} keyserver=p80.pool.sks-keyservers.net state=present

- name: Install https apt transport package
  apt: pkg=apt-transport-https state=present update_cache=yes

- name: Determine OS short code name
  command: 'lsb_release -cs'
  register: code_name

- name: Determine OS distribution name
  shell: "lsb_release -is | tr '[:upper:]' '[:lower:]'"
  register: os_distro

- debug:
    msg: "Repo qualifier is: {{os_distro.stdout}}-{{code_name.stdout}}"
    verbosity: 2 # when verbose option is vv

- name: Determine OS kernel release
  command: 'uname -r'
  register: kernel_release

- name: Install 'linux-image-extra' package if Ubuntu trusty
  apt: pkg=linux-image-extra-{{kernel_release.stdout}} state=present
  when: code_name.stdout == "trusty"

- name: Add docker repo
  apt_repository: repo='deb {{docker_repo}} {{os_distro.stdout}}-{{code_name.stdout}} main' state=present

- name: Install 'docker-engine'
  apt: pkg={{docker_apt_package}} state=present update_cache=yes

- name: Add user to docker group
  user: name={{ansible_ssh_user}} groups=docker append=yes
  register: add_group
