---
- name: Add third party Java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Auto accept license
  shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | /usr/bin/debconf-set-selections

- name: Install Oracle Java 8 JDK
  apt: pkg=oracle-java8-installer state=present update_cache=yes
  